export const events = {
  GET_EXTENSION_ID: "HORSY_GET_EXTENSION_ID",
  SAVE_SETTING: "HORSY_SAVE_SETTING",
  UPDATE_SETTING: "HORSY_UPDATE_SETTING",
  GET_SETTING: "HORSY_GET_SETTING",
};

export const CHAT_INPUT_ELEMENT_CLASS_NAME = "chat-input";
